services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # depends_on:
    #   - backend-api

  backend-api:
    build: ./backend/api
    ports:
      - 8000:8000
    environment:
      - ENV=production
      - DB_HOST=backend-db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_HOST=backend-redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - backend-db
      - backend-redis

  backend-db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend-redis:
    build: ./backend/redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: